# Generated by Django 5.2 on 2025-04-19 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'bible.bibleversion',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('testament', models.CharField(choices=[('신', '신약'), ('구', '구약약')], max_length=10)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'bible.book',
                'ordering': ['order'],
                'unique_together': {('slug',)},
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.book')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.version')),
            ],
            options={
                'db_table': 'bible.verse',
                'ordering': ['version', 'book', 'chapter', 'number'],
                'unique_together': {('version', 'book', 'chapter', 'number')},
            },
        ),
    ]
