# Generated by Django 5.2 on 2025-04-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='testament',
            field=models.CharField(choices=[('신', '신약'), ('구', '구약')], max_length=10),
        ),
    ]
