# Generated by Django 5.2 on 2025-04-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_alter_book_testament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='order',
        ),
        migrations.AlterField(
            model_name='book',
            name='testament',
            field=models.CharField(choices=[('NT', 'New Testament'), ('OT', 'Old Testament')], max_length=10),
        ),
    ]
