# Generated by Django 5.2 on 2025-04-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_alter_book_options_alter_version_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
